config/routes.rb
Rails.application.routes.draw do
  get 'users', to: 'users#index'
  get 'dashboard', to: 'dashboard#index', as: 'dashboard'

  devise_for :users

  resources :course_types, except: [:show, :destroy]
  resources :courses, except: :show
  resources :orders, only: [:index, :new, :create]
  get 'orders/menu', to: 'orders#menu'
  namespace :api do
    resources :orders, only: :index
  end

  root 'dashboard#index'
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :course_type, inverse_of: :courses
  has_many :line_items
  has_many :orders, through: :line_items

  validates :course_type, presence: true
  validates :name, length: { in: 3..30 }, presence: true
  validates :price, numericality: true, presence: true

  scope :today, -> { where(deleted_at: nil) }
  scope :for_date, ->(date) {
    where('created_at < ?', date).where('deleted_at > ? OR deleted_at IS NULL', date)
  }

  def destroy_saver
    self.deleted_at = DateTime.now
    save
  end

  def update_saver(arg)
    Course.create(name: arg['name'] || name,
                  price: arg['price'] || price,
                  course_type_id: arg['course_type_id'] || course_type_id)
    reload
    destroy_saver
  end
end

app/models/course_type.rb
class CourseType < ActiveRecord::Base
  has_many :courses, inverse_of: :course_type

  validates :name, length: { in: 1..20 }, presence: true
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :course

  before_save :ensure_one_course_for_each_course_type_in_one_order

  private

  def ensure_one_course_for_each_course_type_in_one_order
    if order.courses.exists?(course_type_id: course.course_type.id)
      errors.add :base, 'Only one course from each course types'
      return false
    else
      return true
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user, inverse_of: :orders
  has_many :line_items
  has_many :courses, through: :line_items
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader

  has_many :orders, inverse_of: :user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, length: { in: 3..20 }, presence: true

  before_save { self.admin = true unless User.any? }
end

app/controllers/api/orders_controller.rb
class Api::OrdersController < ApplicationController
  before_action :check_key

  def index
    today = Date.today
    @orders = Order.where(created_at: today..(today + 1.day))
  end

  private

  def check_key
    render json: {
      error: 'Unauthorized, check the key',
      status: 401
    }, status: :unauthorized unless Rails.application.secrets.orders_api_key == params[:key]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u|
      u.permit(
               :name,
               :email,
               :password,
               :password_confirmation,
               :remember_me,
               :avatar,
               :avatar_cache
              )
    }
    devise_parameter_sanitizer.for(:account_update) { |u|
      u.permit(
               :name,
               :email,
               :password,
               :password_confirmation,
               :current_password,
               :avatar,
               :avatar_cache
              )
    }
  end

  def ensure_admin!
    unless current_user.admin?
      sign_out current_user

      redirect_to root_path, alert: 'Access denied, you must be admin!'
      return false
    end
  end
end

app/controllers/course_types_controller.rb
class CourseTypesController < ApplicationController
  before_action :authenticate_user!, :ensure_admin!

  def index
    @course_types = CourseType.all
  end

  def new
    @course_type = CourseType.new
  end

  def edit
    @course_type = CourseType.find(params[:id])
  end

  def create
    @course_type = CourseType.new(course_type_params)

    if @course_type.save
      redirect_to course_types_url, notice: 'Course type was successfully created.'
    else
      render :new
    end
  end

  def update
    @course_type = CourseType.find(params[:id])

    if @course_type.update(course_type_params)
      redirect_to course_types_url, notice: 'Course type was successfully updated.'
    else
      render :edit
    end
  end

  private

  def course_type_params
    params.require(:course_type).permit(:name)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!, :ensure_admin!
  before_action :set_course, only: [:edit, :update, :destroy]

  def index
    @courses = Course.today
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to courses_url, notice: 'Course was successfully created.'
    else
      render :new
    end
  end

  def update
    if @course.update_saver(course_params)
      redirect_to courses_url, notice: 'Course was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @course.destroy_saver
    redirect_to courses_url, notice: 'Course was successfully destroyed.'
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name, :price, :course_type_id)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_admin!, only: :index

  def index
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @orders = Order.where(created_at: @date..(@date + 1.day))
  end

  def menu
    @date = params[:date]
    @courses = if @date
                 Course.for_date(@date).group_by(&:course_type)
               else
                 Course.today.group_by(&:course_type)
               end
  end

  def new
    @order = Order.new
    @courses = Course.today.group_by(&:course_type)
  end

  def create
    order = current_user.orders.new
    course_ids = order_params.values
    order.courses << Course.today.find(course_ids)
    if order.save
      redirect_to dashboard_url, notice: 'Order was successfully created.'
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:Courses).permit!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :ensure_admin!

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_active?(link_path)
   current_page?(link_path) ? "active" : ""
  end

  def alert_class_for(flash_type)
    {
      :success => 'alert-success',
      :error => 'alert-danger',
      :alert => 'alert-warning',
      :notice => 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

end

app/helpers/course_types_helper.rb
module CourseTypesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def total_sum(orders)
    orders.inject(0) { |sum, order| sum + order.courses.sum(:price) }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/course_types/_form.html.haml
= simple_form_for(@course_type) do |f|
  = f.error_notification

  = f.input :name

  = link_to 'Back', course_types_path, class: 'btn btn-default'
  = f.button :submit, class: 'btn btn-primary'

app/views/course_types/edit.html.haml
.center-block.col-md-4{:style => "float: none"}
  .panel.panel-default
    .panel-heading Editing course type:
    .panel-body
      = render 'form'

app/views/course_types/index.html.haml
.center-block.col-md-4{:style => "float: none"}
  .panel.panel-default
    .panel-heading Course types:
    .panel-body
      %table.table.table-striped.table-hover.table-condensed
        %thead
          %tr
            %th #
            %th Name
            %th
        %tbody
          - @course_types.each_with_index do |course_type, index|
            %tr
              %th{scope: 'row'}
                = index + 1
              %td= course_type.name
              %td= link_to 'Edit', edit_course_type_path(course_type), class: 'btn btn-success btn-xs'

      = link_to 'New Course type', new_course_type_path, class: 'btn btn-primary'

app/views/course_types/new.html.haml
.center-block.col-md-4{:style => "float: none"}
  .panel.panel-default
    .panel-heading New course type:
    .panel-body
      = render 'form'

app/views/courses/_form.html.haml
= simple_form_for(@course) do |f|
  = f.error_notification

  = f.input :name
  = f.input :price
  = f.association :course_type, prompt: "Choose a type"

  = link_to 'Back', courses_path, class: 'btn btn-default'
  = f.button :submit, class: 'btn btn-primary'

app/views/courses/edit.html.haml
.center-block.col-md-6{:style => "float: none"}
  .panel.panel-default
    .panel-heading Editing course:
    .panel-body
      = render 'form'

app/views/courses/index.html.haml
.center-block.col-md-6{:style => "float: none"}
  .panel.panel-default
    .panel-heading Menu:
    .panel-body
      %table.table.table-striped.table-hover.table-condensed
        %thead
          %tr
            %th #
            %th Name
            %th Price
            %th Type
            %th
            %th
        %tbody
          - @courses.each_with_index do |course, index|
            %tr
              %th{scope: 'row'}
                = index + 1
              %td= course.name
              %td= number_to_currency course.price, precision: 2
              %td= course.course_type.name
              %td= link_to 'Edit', edit_course_path(course), class: 'btn btn-success btn-xs'
              %td= link_to 'Destroy', course, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger btn-xs'
      = link_to 'New Course', new_course_path, class: 'btn btn-primary'

app/views/courses/new.html.haml
.center-block.col-md-4{:style => "float: none"}
  .panel.panel-default
    .panel-heading New course:
    .panel-body
      = render 'form'

app/views/dashboard/index.html.haml
%h1 Dashboard
= month_calendar do |date|
  - unless date.sunday? || date.saturday?
    = link_to date.day, controller: 'orders', action: 'menu', date: date if date < Date.today
    = link_to date.day, new_order_path if date == Date.today
    = date.day if date > Date.today
    - if current_user.admin?
      %p
      = link_to 'orderds', controller: 'orders', action: 'index', date: date if date <= Date.today

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LunchOrdering
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      %nav.navbar.navbar-default
        .container-fluid
          .navbar-header
            %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to "Lunch Ordering", root_path, class: 'navbar-brand'
          #navbar.navbar-collapse.collapse
            %ul.nav.navbar-nav.navbar-right
              - if user_signed_in?
                %li{class: is_active?(dashboard_path) + is_active?(root_path)}
                  = link_to "Dashboard", dashboard_path
                %li{class: is_active?(edit_user_registration_path)}
                  = link_to "Profile", edit_user_registration_path
                - if current_user.admin?
                  %li{class: is_active?(course_types_path)}
                    = link_to "Course types", course_types_path
                  %li{class: is_active?(courses_path)}
                    = link_to "Menu", courses_path
                  %li{class: is_active?(users_path)}
                    = link_to "Users", users_path
                  %li{class: is_active?(orders_path)}
                    = link_to "Orders", orders_path
                %li
                  = link_to "#{current_user.name} Logout", destroy_user_session_path
              - else
                %li{class: is_active?(new_user_session_path)}
                  = link_to "Login", new_user_session_path

    .container
      .row
        - flash.each do |type, message|
          %div{:class => "alert #{alert_class_for(type)} alert-dismissible fade in"}
            %button.close{"data-dismiss" => "alert", :type => "button"}
              %span{"aria-hidden" => "true"} ×
              %span.sr-only Close
            = message

        = yield

      .row
        %hr
        %footer.footer
          %p &copy; Belkot Oleh 2015
        = debug(params) if Rails.env.development?

app/views/orders/index.html.haml
= link_to '<<', controller: 'orders', action: 'index', date: @date.yesterday
= @date
= link_to '>>', controller: 'orders', action: 'index', date: @date.tomorrow

.panel.panel-default
  .panel-heading Listing orders:
  .panel-body
    %table.table.table-striped.table-hover.table-condensed
      %thead
        %tr
          %th #
          %th DateTime
          %th User name
          %th User email
          %th Courses
          %th Price
      %tbody
        - @orders.each_with_index do |order, index|
          %tr
            %th{scope: 'row'}
              = index + 1
            %td= time_tag order.created_at.to_time
            %td= order.user.name
            %td= order.user.email
            %td
              %table
                %tbody
                  - order.courses.each do |course|
                    %tr
                      %td= "#{course.course_type.name}:"
                      %td
                        = course.name
                        \ -
                      %td
                        = number_to_currency course.price, precision: 2
            %td= number_to_currency order.courses.sum(:price), precision: 2
      %tfoot
        %tr
          %td
          %td
          %td
          %td
          %td
          %td
            Total:
            = number_to_currency total_sum(@orders), precision: 2

app/views/orders/menu.html.haml
.panel.panel-default
  .panel-heading
    Menu for
    = @date
    \:
  .panel-body
    .row
      - @courses.each do |course_type, courses|
        .col-md-4
          .panel.panel-default
            .panel-heading= course_type.name
            .panel-body
              - courses.each do |course|
                = course.name
                \-
                = number_to_currency course.price, precision: 2
                %br

app/views/orders/new.html.haml
.panel.panel-default
  .panel-heading Menu:
  .panel-body
    = form_for @order do |f|
      .row
        - @courses.each do |course_type, courses|
          .col-md-4
            .panel.panel-default
              .panel-heading= course_type.name
              .panel-body
                - courses.each do |course|
                  .radio
                    %label
                      = radio_button 'Courses', course_type.name, course.id
                      = course.name
                      \-
                      = number_to_currency course.price, precision: 2
                      / = label 'Courses', "#{course_type.name}_#{course.id}", course.name
      .row
        .col-md-6
          = f.submit 'Submit', class: 'btn btn-primary'

app/views/users/index.html.haml
.center-block.col-md-10{:style => "float: none"}
  .panel.panel-default
    .panel-heading Users:
    .panel-body
      %table.table.table-striped.table-hover.table-condensed
        %thead
          %tr
            %th #
            %th Avatar
            %th Type
            %th Name
            %th Email
            %th Time
        %tbody
          - @users.each_with_index do |user, index|
            %tr
              %th{scope: 'row'}
                = index + 1
              %td
                - if user.avatar.url.present?
                  = image_tag(user.avatar.url, size: "64")
              %td= user.admin? ? "Admin" : "User"
              %td= user.name
              %td= user.email
              %td
                Created:
                = time_tag user.created_at.to_time
                %br
                Updated:
                = time_tag user.updated_at.to_time